source "https://rubygems.org"

gem "jekyll", "~> 3.7"
gem "kramdown-parser-gfm"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.2"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-feed", "~> 0.10"
gem "jemoji", "~> 0.10"
gem "jekyll-include-cache", "~> 0.1"
gem "webrick", "~> 1.7"
